[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://contact-management-app-gcq2.onrender.com/"  # Replace with your actual backend URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
